name: "Build and Push Docker Image"
description: "Builds and pushes Docker images to ECR, GCR, ACR, or Docker Hub using Python"

inputs:
  registry:
    required: true
    description: "Registry type: ecr | gcr | acr | dockerhub"
  image:
    required: true
    description: "Image name (e.g., my-app)"
  image-version:
    required: true
    description: "Tag/version of the image"
  image-dockerfile:
    required: true
    description: "Path to the Dockerfile"
  args:
    required: false
    description: "Additional build arguments"
  image-previous-version:
    required: false
    description: "Previous image version (for build cache)"
  aws-role:
    required: false
    description: "AWS IAM role to assume"
  aws-region:
    required: false
    description: "AWS region"
  project-id:
    required: false
    description: "GCP project ID"
  username:
    required: false
    description: "Username (Docker Hub / ACR / GCR)"
  password:
    required: false
    description: "Password or token (Docker Hub / ACR / GCR)"
  registry-url:
    required: false
    description: "Custom registry URL (e.g., for ACR)"

outputs:
  image:
    description: "The full image name"
    value: ${{ steps.build.outputs.image }}

runs:
  using: composite

  steps:
  
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python and Docker dependencies
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3 python3-pip
        python3 --version
        pip3 install --upgrade pip

    - name: Execute Python script
      id: build
      shell: bash
      run: python3 main.py
